#!/bin/sh
#
# perf-compare.sh - compare the encoding speed of a baseline and a candidate
# LAME build.
#
# It takes one cell of two build matrices generated by gen-build-matrix.sh -
# a baseline tree and a candidate tree - encodes the same input file with
# both, and reports whether the candidate is faster, slower, or
# indistinguishable.
#
# Speed is only half of the answer: unless a change is meant to alter the
# output, a faster encoder that changes the bitstream is a bug rather than an
# optimization. The bitstreams are therefore compared first and the result is
# reported alongside the timings.
#
# The measurement protocol is one warmup run, at least ten hot runs, and a
# coefficient of variation deciding whether the result can be trusted at all.
#
# Part of the LAME distribution.  No warranty; see COPYING.

set -u

prog=$(basename "$0")

usage() {
	cat <<EOF
Usage: $prog -o DIR -n DIR [-c CELL] -i FILE [-e ARGS] [-r N] [-l] [-h]

  -o DIR     Baseline build matrix, as created by gen-build-matrix.sh.
  -n DIR     Candidate build matrix, laid out the same way.
  -c CELL    Cell to compare, e.g. "gcc/full". A bare cell name is accepted
             when only one compiler provides it. (default: gcc/full)
  -i FILE    Input audio file. Use several minutes of real music rather than
             a short clip.
  -e ARGS    Encoder arguments; several go in one argument, as they are split
             on the spaces between them, e.g. -e "-V0 -m j". (default: -V2)
  -r N       Hot runs, at least 10. (default: 10)
  -l         List the cells both matrices have in common and exit.
  -h         Show this help and exit.

Both matrices must be built from their respective sources first. Only the
encoder differs between the two runs: same input, same arguments, same host.
EOF
}

# --- option parsing ---------------------------------------------------------

old=
new=
cell=gcc/full
input=
encargs=-V2
runs=10
list=no

while getopts "o:n:c:i:e:r:lh" opt; do
	case "$opt" in
		o)
			old=$OPTARG
			;;
		n)
			new=$OPTARG
			;;
		c)
			cell=$OPTARG
			;;
		i)
			input=$OPTARG
			;;
		e)
			encargs=$OPTARG
			;;
		r)
			runs=$OPTARG
			;;
		l)
			list=yes
			;;
		h)
			usage
			exit 0
			;;
		*)
			usage >&2
			exit 2
			;;
	esac
done

# --- prerequisites ----------------------------------------------------------
#
# hyperfine runs and times the encoder.
# ministat turns the two sets of hot runs into a confidence interval; where it
# is missing, hyperfine's own summary is reported instead and the run stands.

if ! command -v hyperfine >/dev/null 2>&1; then
	echo "$prog: hyperfine not found - it runs and times the encoder." >&2
	echo "$prog: FreeBSD: pkg install hyperfine; MSYS2: pacman -S mingw-w64-ucrt-x86_64-hyperfine" >&2
	echo "$prog: Debian/Ubuntu: apt install hyperfine" >&2
	exit 1
fi

ministat=
if command -v ministat >/dev/null 2>&1; then
	ministat=ministat
else
	echo "$prog: WARNING: ministat not found - reporting hyperfine's own" >&2
	echo "$prog:          comparison instead of a confidence interval." >&2
	echo "$prog:          FreeBSD has it in base; Debian/Ubuntu: apt install ministat" >&2
fi

# --- argument checks --------------------------------------------------------

if [ -z "$old" ] || [ -z "$new" ]; then
	echo "$prog: both -o and -n are required." >&2
	usage >&2
	exit 2
fi
for d in "$old" "$new"; do
	if [ ! -d "$d" ]; then
		echo "$prog: '$d' is not a directory." >&2
		exit 1
	fi
done
old=$(cd "$old" && pwd)
new=$(cd "$new" && pwd)
if [ "$old" = "$new" ]; then
	echo "$prog: the two matrices are the same directory." >&2
	exit 1
fi

# --- locating the encoder ---------------------------------------------------
#
# Print the cells a matrix holds, as "<compiler>/<cell>" paths. A cell is
# recognized by its config.status, which configure leaves in every build
# directory: a cell that was generated but never built has nothing to time.
matrix_cells() {
	find "$1" -mindepth 3 -maxdepth 3 -name config.status 2>/dev/null |
		while read -r f; do
			d=$(dirname "$f")
			echo "${d#$1/}"
		done | sort
}

if [ "$list" = yes ]; then
	echo "Cells in both matrices:"
	comm -12 "$(matrix_cells "$old" > /tmp/$$.o; echo /tmp/$$.o)" \
		"$(matrix_cells "$new" > /tmp/$$.n; echo /tmp/$$.n)" | sed 's/^/  /'
	rm -f /tmp/$$.o /tmp/$$.n
	exit 0
fi

# Resolve a bare cell name against the compilers present, so that "full" works
# where it is unambiguous and a clash is reported rather than guessed at.
resolve_cell() {
	_m=$1
	_c=$2
	if [ -d "$_m/$_c" ]; then
		echo "$_c"
		return 0
	fi
	_hits=$(matrix_cells "$_m" | grep "/$_c\$" || true)
	_n=$(echo "$_hits" | grep -c . || true)
	if [ "$_n" -eq 1 ]; then
		echo "$_hits"
		return 0
	fi
	if [ "$_n" -eq 0 ]; then
		echo "$prog: no cell '$_c' in $_m. Available:" >&2
		matrix_cells "$_m" | sed 's/^/  /' >&2
	else
		echo "$prog: '$_c' is ambiguous in $_m:" >&2
		echo "$_hits" | sed 's/^/  /' >&2
	fi
	return 1
}

# The encoder of a cell, and the library path it has to run with.
#
# With dynamic frontends - the default - libtool leaves a wrapper shell script
# named "lame" behind and puts the real executable in .libs. Timing the
# wrapper would time a shell start-up per run, but the executable cannot
# simply be run in its place: it is linked against an installed libmp3lame if
# one exists, so it would silently measure that library rather than the build
# under test. Running it with the cell's own library directory first on the
# search path is what the wrapper does, without the shell.
find_encoder() {
	_d="$1/$2/frontend"
	_lib="$1/$2/libmp3lame/.libs"
	if [ ! -d "$_d" ]; then
		echo "$prog: '$_d' not found - is the cell built?" >&2
		return 1
	fi
	for _f in "$_d/lame" "$_d/lame.exe"; do
		if [ ! -f "$_f" ]; then
			continue
		fi
		case $(head -c 2 "$_f" 2>/dev/null) in
			'#!')
				for _r in "$_d/.libs/lame" "$_d/.libs/lame.exe"; do
					if [ -x "$_r" ]; then
						echo "$_r|$_lib"
						return 0
					fi
				done
				# A wrapper with nothing behind it: use it as it is.
				echo "$_f|"
				return 0
				;;
			*)
				echo "$_f|"
				return 0
				;;
		esac
	done
	echo "$prog: no encoder under '$_d' - is the cell built?" >&2
	return 1
}

old_cell=$(resolve_cell "$old" "$cell") || exit 1
new_cell=$(resolve_cell "$new" "$cell") || exit 1

old_enc=$(find_encoder "$old" "$old_cell") || exit 1
new_enc=$(find_encoder "$new" "$new_cell") || exit 1

old_bin=${old_enc%|*}
old_libpath=${old_enc#*|}
new_bin=${new_enc%|*}
new_libpath=${new_enc#*|}

if [ -z "$input" ]; then
	echo "$prog: -i INPUT is required." >&2
	exit 2
fi
if [ ! -r "$input" ]; then
	echo "$prog: cannot read input file '$input'." >&2
	exit 1
fi

if [ "$runs" -lt 10 ] 2>/dev/null; then
	echo "$prog: WARNING: -r $runs is below the 10 hot runs a result needs." >&2
fi

# --- workspace --------------------------------------------------------------

work=$(mktemp -d 2>/dev/null || mktemp -d -t lameperf)
if [ -z "$work" ] || [ ! -d "$work" ]; then
	echo "$prog: cannot create a temporary directory." >&2
	exit 1
fi
trap 'rm -rf "$work"' 0 1 2 3 15

# Build the command line for one encoder. The library path only needs to be
# set where the encoder was found next to an uninstalled shared library.
enc_cmd() {
	# $1 = binary, $2 = library path, $3 = output file
	if [ -n "$2" ]; then
		echo "env LD_LIBRARY_PATH='$2' '$1' --quiet $encargs '$input' '$3'"
	else
		echo "'$1' --quiet $encargs '$input' '$3'"
	fi
}

old_cmd=$(enc_cmd "$old_bin" "$old_libpath" "$work/old.mp3")
new_cmd=$(enc_cmd "$new_bin" "$new_libpath" "$work/new.mp3")

echo "baseline : $old_bin"
echo "candidate: $new_bin"
echo "input    : $input"
echo "arguments: $encargs"
echo "hot runs : $runs (after 1 warmup)"
echo

# --- bitstream comparison ---------------------------------------------------

if ! eval "$old_cmd" || ! eval "$new_cmd"; then
	echo "$prog: an encoder failed to run." >&2
	exit 1
fi

if cmp -s "$work/old.mp3" "$work/new.mp3"; then
	bitstream="identical"
else
	bitstream="DIFFERENT"
fi

# --- timing -----------------------------------------------------------------

json="$work/hyperfine.json"
if ! hyperfine --warmup 1 --runs "$runs" --style basic \
	-n baseline "$old_cmd" \
	-n candidate "$new_cmd" \
	--export-json "$json" > "$work/hyperfine.txt" 2>&1; then
	cat "$work/hyperfine.txt" >&2
	echo "$prog: hyperfine failed." >&2
	exit 1
fi

# Per-run timings live only in the JSON export; the CSV export carries the
# summary statistics alone.
extract_times() {
	# $1 = json, $2 = 0-based index of the result
	awk -v want="$2" '
		/"times": \[/ { grab = (idx == want); intimes = 1; next }
		intimes && /\]/ { intimes = 0; if (grab) exit; idx++; next }
		intimes && grab { gsub(/[ ,]/, ""); if (length($0)) print }
	' "$1"
}

extract_times "$json" 0 > "$work/old.times"
extract_times "$json" 1 > "$work/new.times"

stats() {
	awk '{ n++; s += $1; q += $1 * $1 }
	     END {
	         if (n < 2) { print "0 0 0"; exit }
	         m = s / n
	         sd = sqrt((q - n * m * m) / (n - 1))
	         printf "%.6f %.6f %.4f\n", m, sd, (m > 0 ? 100 * sd / m : 0)
	     }' "$1"
}

set -- $(stats "$work/old.times")
old_mean=$1; old_sd=$2; old_cv=$3
set -- $(stats "$work/new.times")
new_mean=$1; new_sd=$2; new_cv=$3

# --- report -----------------------------------------------------------------

printf 'baseline : %8.3f s  +/- %.3f  (CV %.2f%%)\n' "$old_mean" "$old_sd" "$old_cv"
printf 'candidate: %8.3f s  +/- %.3f  (CV %.2f%%)\n' "$new_mean" "$new_sd" "$new_cv"
echo

if [ -n "$ministat" ]; then
	echo "--- ministat (baseline vs candidate, 95% CI) ---"
	"$ministat" -c 95 -w 74 "$work/old.times" "$work/new.times" 2>&1 || true
else
	echo "--- hyperfine summary ---"
	sed -n '/Summary/,$p' "$work/hyperfine.txt"
fi
echo

echo "bitstream: $bitstream"
if [ "$bitstream" = DIFFERENT ]; then
	echo "  The two builds do not encode to the same bits. Unless this change is"
	echo "  meant to alter the output, that is a bug and outranks any speedup."
fi

# The coefficient of variation decides whether the numbers mean anything at
# all.
worst_cv=$(awk -v a="$old_cv" -v b="$new_cv" 'BEGIN { print (a > b ? a : b) }')
echo
awk -v cv="$worst_cv" -v runs="$runs" '
	BEGIN {
		if (cv <= 2) {
			printf "measurement: CV %.2f%% - trustworthy.\n", cv
			exit 0
		}
		if (cv <= 5) {
			printf "measurement: CV %.2f%% - borderline. Re-run with -r 20;\n", cv
			print  "             frequency scaling or a background process is the"
			print  "             usual cause rather than too few samples."
			exit 0
		}
		printf "measurement: CV %.2f%% - do not trust this run.\n", cv
		print  "             More samples will not help: something is wrong with the"
		print  "             measurement environment (thermal throttling, turbo boost,"
		print  "             background load, a non-performance power plan)."
		exit 1
	}'
cv_status=$?

if [ "$bitstream" = DIFFERENT ]; then
	exit 1
fi
exit $cv_status
